// Core booking types shared across the booking app

export interface Service {
  id: string;
  name: string;
  price: string;
  duration: number;
  description?: string;
}

export interface Slot {
  virtual_id?: string; // vId generated by frontend
  starts_at: string;
  ends_at: string;
  staff_id?: string;
  service_id: string;
}

export interface SlotsByDate {
  [dateKey: string]: Slot[];
}

export interface Clinic {
  id: string;
  name: string;
  slug: string;
  tenant_schema: string;
  template_id?: string;
  theme?: ClinicTheme;
  logo_url?: string;
  tagline?: string;
  whatsapp_number?: string;
  show_powered_by?: boolean;
}

export interface ClinicTheme {
  template?: string;
  primary_color?: string;
  accent_color?: string;
  background_color?: string;
  text_color?: string;
  font_family?: string;
}

export interface ConfirmedBooking {
  id: string;
  reference_number?: string;
  patient_phone?: string;
  patient_name?: string;
  status: 'PENDING' | 'CONFIRMED' | 'CANCELLED' | 'NO_SHOW';
  starts_at?: string;
  ends_at?: string;
  created_at?: string;
  service?: Service;
}

export type BookingStep = 1 | 2 | 3 | 4 | 5;

export interface BookingState {
  currentStep: BookingStep;
  selectedService: Service | null;
  selectedSlot: Slot | null;
  selectedDate: Date;
  patientName: string;
  patientPhone: string;
  bookingId: string | null;
  sessionId: string;
  isLoading: boolean;
  error: string | null;
}

export interface BookingActions {
  selectService: (service: Service) => void;
  selectDate: (date: Date) => void;
  selectSlot: (slot: Slot) => Promise<void>;
  goBack: () => void;
  submitPatientInfo: (name: string, phone: string) => Promise<void>;
  verifyOTP: (otp: string) => Promise<void>;
  retryOTP: () => Promise<void>;
  reset: () => void;
}

export interface UseBookingFlowReturn extends BookingState, BookingActions {}
